### PR TITLE
asking a question

### PR DESCRIPTION
**Pull request by malikrohit16**
what things one has to do in order to make this crawler work

### CODE REVIEW

**Comment by joseangeldiazg** [comment]
Hi Malikrohit! This crawler works on scrapinghub but has some bugs. You can use it in your local machine: 
- pull the repository. 
- cd the folder.
- install the dependences.  
- Finally run: scrapy crawl stream-filter -a track=#yourhashtag

**Comment by malikrohit16** [comment]
I tried to run it but it shows that argument track not set. can you please tell me how to set track

**Comment by malikrohit16** [comment]
and one more question that whether it will scrape out all the tweets or only first 20.
thanks

**Comment by joseangeldiazg** [comment]
You have to use the scrpper like _scrapy crawl stream-filter -a track=#yourhashtag_ as you can see the track argument is set. This scrapper can scrape out all the tweets about a topic.

**Comment by malikrohit16** [comment]
thanks for the help

**Pull request merged**
